[update] add ColorDialog
It needed to setup for using ColorDialog according to the following error message.

ERROR: No native ColorDialog implementation available.
Qt Labs Platform requires Qt Widgets on this setup.
Add 'QT += widgets' to .pro and create QApplication in main().